-- producto para crear
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('DEDAKJ Concentrador de Oxígeno 1-7L',  'Más del 30-93% de pureza de oxígeno, alcance ajustable 1-7L /min', 270.44, 100, 'http://www.aicija.com/gp2-images/concentrador-aire.jpg', 1);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('KEMPER - Botella de oxígeno 110 bar Pack x 3', 'Pack de 3 botellas de oxígeno con válvula KEMPER. Presión media de 110 bar. Conexión: M 10 x 1. No recargable.', 99.00, 100, 'http://www.aicija.com/gp2-images/botellas-oxigeno.jpg', 1);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Boost Oxygen', 'Botella de Oxígeno Portátil, Lata de Oxigeno 95% Puro y Natural - Concentración, Recuperación, Energía, Estado de Ánimo, Mediano - 5L- Menta', 26.59, 100, 'http://www.aicija.com/gp2-images/botella-metal-oxigeno.jpg', 1);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Silla de ruedas manual', 'Transporte', 650.00, 10, 'http://www.aicija.com/gp2-images/silla-ruedas.jpg', 2);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Silla de ruedas eléctrica', 'Transporte', 3550.00, 12, 'http://www.aicija.com/gp2-images/silla-electrica.jpg', 2);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Andadera', 'Transporte', 550.00, 5, 'http://www.aicija.com/gp2-images/andador.jpg', 2);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Barra de apoyo abatible', 'Barra abatible de giro vertical con portarrollos', 58.34, 10, 'http://www.aicija.com/gp2-images/barra-abatible.jpg' ,3);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Silla salva escaleras', 'aparato mecanico para subir escaleras',3285.00, 70, 'http://www.aicija.com/gp2-images/silla-salva.jpg', 3);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Ascensor acuatico', 'Ascensor para poder entrar a la piscina', 4132.00, 30, 'http://www.aicija.com/gp2-images/escalera-piscina.jpg', 3);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Par de reposabrazos para silla', 'Par de reposabrazos para silla de ruedas o silla con brazos, 34 x 34 cm', 47.95, 125 ,'http://www.aicija.com/gp2-images/reposabrazos-silla.jpg', 4);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('2 Baterías de gel', '2 Baterías de gel para silla de ruedas Cenit y Lyra | 12V20Ah | PBCG12-20', 104.95, 95, 'http://www.aicija.com/gp2-images/baterias-gel.jpg', 4);
INSERT INTO productos (nombre, descripcion, precio, stock, image_URL, categoria_id) VALUE ('Regulador-Caudalímetro', 'Regulador-Caudalímetro 15 LPM O2 MP-22-1', 138.00, 27, 'http://www.aicija.com/gp2-images/regulador-caudalimetro.jpg', 4);
